# Generated by Django 3.2.6 on 2021-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='homepage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='owner_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='repo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.TextField(blank=True),
        ),
    ]
