# Generated by Django 3.2.6 on 2021-12-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20211218_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
