# Generated by Django 3.2.6 on 2021-12-20 16:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0014_auto_20211220_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepos',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=4000), size=1000), size=1000),
        ),
        migrations.AlterField(
            model_name='githubrepos',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=4000), size=1000), size=1000),
        ),
    ]
