# Generated by Django 3.2.6 on 2021-12-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0015_auto_20211220_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepos',
            name='languages',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='githubrepos',
            name='topics',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
