# Generated by Django 3.2.6 on 2021-12-18 12:48

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20211218_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='content',
            field=separatedvaluesfield.models.SeparatedValuesField(blank=True, max_length=800),
        ),
    ]
