# Generated by Django 3.2.6 on 2021-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_repository_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='full_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
