# Generated by Django 3.2.6 on 2021-12-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_remove_repository_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
