# Generated by Django 3.2.6 on 2021-12-20 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_githubrepos'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepos',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='githubrepos',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), default=[], size=None),
            preserve_default=False,
        ),
    ]
